Repository CS342/2024-Intake, pull requests merged in 2024-01, with the labels that each got.

#2 Fix Firebase Project ID
  .firebaserc
  Intake/Supporting Files/GoogleService-Info.plist
Labels: bug

#7 Update README & CodeCov Setup
  README.md
  codecov.yml
Labels: documentation

#5 Task3
  Intake.xcodeproj/project.pbxproj
  Intake/IntakeDelegate.swift
  Intake/Onboarding/NotificationPermissions.swift
  Intake/Onboarding/OnboardingFlow.swift
  Intake/Resources/Localizable.xcstrings
Labels: enhancement

#6 Assignment 1, Task 2 - Update onboarding flow
  Intake/Onboarding/InterestingModules.swift
  Intake/Onboarding/Welcome.swift
  Intake/Resources/Localizable.xcstrings
Labels: enhancement
